site_name: Doggies as a Service (DaaS)
site_url: ""
use_directory_urls: false
theme: 
   name: material
   logo: assets/cdl-logo.png
   font: 
     text: Merriweather Sans
     code: Red Hat Mono
   features: 
    - navigation.paths
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch 
    - navigation.instant.progress

repo_url: https://gitlab.com/cheshire-datasystems/insurance-retail/squad-8/documents-as-a-service/documents-as-a-service
repo_name: GitLab
edit_uri: blob/master/docs

plugins:
  - search

nav:
  - Home: index.md 
  - Get started: 
    - What this API does: get-started.md
    - Obtain Access Tokens: authentication.md
  - Common Use Cases (endpoints):
    - Determine Document Storage: document-storage-options.md 
    - Retrieve and Manage Documents: document-retrieve-manage.md
    - Retrieve and Manage Templates: document-templates-manage.md
  - Reference:
    - Data Structures: data-structures.md
    - API Reference: https://cdl-justice.dev.cdlcloud.co.uk/ 
    - Error Codes: error-codes.md
    - Change History: change-history.md

copyright: Copyright &copy; 2025 Cheshire Datasystems Limited

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version: 
    provider: mike

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
